
title:            Nate Brennand
description:      Personal website for Nate Brennand. Will discuss programming, school and running.
disqus_shortname: 
#Comment out url when working locally to resolve base urls correctly
url:              http://natebrennand.github.io

# Owner/author information
owner:
  name:           Nate Brennand
  avatar:         "https://0.gravatar.com/avatar/63a82b7c52574ade60a1cf313f50aeb8?d=https%3A%2F%2Fidenticons.github.com%2F5852666c807534925da26d860a1bba16.png&s=420"
  bio:            "I'm a Junior CS student at Columbia University. A Pythonista who likes to build things."
  email:          natebrennand@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        https://twitter.com/NateBrennand
  github:         https://github.com/natebrennand

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-36737775-2

# Links to include in top navigation
# For external links add external: true
#links:
#  - title: External Link
#    url: http://mademistakes.com
#    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

# Amount of post to show on home page
paginate: 10

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

